// sample_application_tenmo/frontend-vue-tenmo-client/src/components/TransferDetail.vue
<template>
  <div>
    <section class="cards-wrapper">
      <div class="card-grid-space">
        <!-- <div class="num">01</div> -->
        <div class="card">
          <div>
            <h2><i v-if="transfer.transferType.desc === 'Request'" class="fas fa-chevron-circle-right" style="color:red"></i>
              <i v-if="transfer.transferType.desc === 'Send'" class="fas fa-chevron-circle-left" style="color:green"></i>
              ${{ transfer.amount }}
            </h2>
            <p>To: {{ transfer.accountTo.user.username }}</p>
            <p>From: {{ transfer.accountFrom.user.username }}</p>
            <p>Ending Balance: {{ transfer.endingBalance }}</p>
            <p>Message: {{ transfer.message }}</p>
            <div class="date">&nbsp;{{ formattedCreateDate }}</div>
            <div class="tags">
              <div class="tag approved" :class="{
                approved: (transfer.transferStatus.desc === 'Approved'),
                rejected: (transfer.transferStatus.desc === 'Rejected'),
                pending: (transfer.transferStatus.desc === 'Pending')
              }">
                {{ transfer.transferStatus.desc }}
              </div>
            </div>
            <div v-if="transfer.transferStatus.desc === 'Pending'">
              <button class="btn btn-approve" @click="approveTransfer()">Approve</button>
              <button class="btn btn-reject" @click="rejectTransfer()">Reject</button>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>
  
<script>
  import transferService from '../services/TransferService';
  import moment from 'moment';

  export default {
    name:'transfer-detail',
    data(){
      return {
        transfer:{
          transferStatus:{},
          transferType:{},
          accountTo:{
            user:{}
          },
          accountFrom:{
            user:{}
          }
        }
      }
    },    
    computed: {
      formattedCreateDate(){
          if (this.transfer.createdDate !== null) {
            return moment(this.transfer.createdDate).format("MMM Do, YYYY hh:mm:ss a");
          }
          return "";
      }
    },
    methods:{
      approveTransfer(){
        this.transfer.transferStatus.id=2;
        this.transfer.transferStatus.desc="Approved";
        this.saveTransfer();
      },
      rejectTransfer(){
        this.transfer.transferStatus.id=3;
        this.transfer.transferStatus.desc="Rejected";
        this.saveTransfer();
      },
      saveTransfer(){        
        transferService.updateTransfer(this.transfer.id, this.transfer).then((response)=>{
          this.transfer = response.data;
          this.$router.push("/");
        });
      }
      
    },
    created(){
        const transferId = this.$route.params.id;
        transferService.getTransfer(parseInt(transferId)).then((response)=>{
          this.transfer = response.data;
        });
      }
    };  
</script>
<style scoped>

</style>

// sample_application_tenmo/frontend-react-tenmo-client/src/components/ui/TransferDetail.js
import { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
//import { useCurrentUser } from "../../context/UserContext";
import moment from 'moment';
import {getTransfer, updateTransfer} from "../../api/TransferService";
import { useNavigate } from "react-router-dom";
import { Button, Card, Col, ListGroup } from 'react-bootstrap';


const TransferDetail = (props) => {
    const { id } = useParams();
    
    const navigate = useNavigate();
  
    const defaultTransfer = {
        transferStatus:{},
        transferType:{},
        accountTo:{
          user:{}
        },
        accountFrom:{
          user:{}
        },
        formattedCreateDate:''
      };
    const [transfer, setTransfer] = useState(defaultTransfer);
    const [callingDetail, setCallingDetail] = useState(-1);
    
    const approveTransfer = (event) => {
        if (event !== undefined) event.preventDefault();
        let localTransfer = transfer;
        localTransfer.transferStatus.id=2;
        localTransfer.transferStatus.desc="Approved";
        setTransfer(localTransfer);
        saveTransfer();
    }

    const rejectTransfer = (event) => {
        if (event !== undefined) event.preventDefault();
        let localTransfer = transfer;
        localTransfer.transferStatus.id=3;
        localTransfer.transferStatus.desc="Rejected";
        setTransfer(localTransfer);
        saveTransfer();
    }

    const saveTransfer = () => {   
        updateTransfer(transfer.id, transfer);
        navigate("/");
    }

    useEffect(() => {
        const getDetails = async () => {
            const transferDetails = async () => {
              if (callingDetail<0) {
                setCallingDetail(0);
                const localDetail = await getTransfer(id);
                localDetail.formattedCreateDate = moment(localDetail.createdDate).format("MMM Do, YYYY hh:mm:ss a");
                setTransfer(localDetail);
                setCallingDetail(1);
              }
            }
            await transferDetails();
          };
          if (callingDetail<0) {
            getDetails()
          }
     }, [callingDetail, id]);
     
    return (
        <>
            <Col>
                
                    <Card className={props.cardColor}>
                        <Card.Header><div>
                                    {(transfer.transferType.desc === 'Request') && 
                                        <i className="fas fa-chevron-circle-right" style={{color:'red'}}></i>
                                    }
                                    {(transfer.transferType.desc === 'Send') && 
                                        <i className="fas fa-chevron-circle-left" style={{color:'green'}}></i>
                                    }
                                ${ transfer.amount }
                                </div></Card.Header>
                        <Card.Body>
                            <Card.Title>{transfer.transferType.desc}</Card.Title>
                            {/* Use divs/custom classes to get custom view, colors, icons */}
                            <ListGroup>
                            <ListGroup.Item>To: { transfer.accountTo.user.username }</ListGroup.Item>
                            <ListGroup.Item>From: { transfer.accountFrom.user.username }</ListGroup.Item>
                            {(transfer.endingBalance) && 
                            <ListGroup.Item>Ending Balance: ${ transfer.endingBalance }</ListGroup.Item>
                            }
                            <ListGroup.Item>Message: { transfer.message }</ListGroup.Item>
                            {(transfer.formattedCreateDate !== "Invalid date") && 
                            <ListGroup.Item>Date: { transfer.formattedCreateDate }</ListGroup.Item>
                            }
                            </ListGroup>
                                
                                {(transfer.transferStatus.desc === 'Pending') && 
                                <>
                                    <Button variant="success" onClick={approveTransfer}>Approve</Button>
                                    {' '}
                                    <Button variant="danger" onClick={rejectTransfer}>Reject</Button>
                                </>
                                }          
                        </Card.Body>
                        <Card.Footer>
                        <div className="tags">
                                    <div className={"tag " +  ((transfer.transferStatus.desc) ? transfer.transferStatus.desc.toLowerCase() : "")}>
                                        { transfer.transferStatus.desc }
                                    </div>
                                </div>                                
                        </Card.Footer>
                    </Card>
                
            </Col> 
        </>
    );
}
export default TransferDetail;
