// sample_application_tenmo/frontend-vue-tenmo-client/src/components/TransferFunds.vue
<template>
    <div>
        <form class="new-transfer-form" v-on:submit.prevent="saveTransfer">
            <div>
            <select v-model="newTransfer.transferType.id"
            style="min-width:300px">
                    <option value="0"></option>
                    <option value="1">Request</option>
                    <option value="2">Send</option>
            </select>
        </div>
        <div>
            <select v-model="actionAccountId" 
                    v-if="newTransfer.transferType.id==1"
                    style="min-width:300px">
                <option v-for="account in accounts" :key="account.id"  
                    :value="account.id"
                    >{{ account.user.username }}</option>
            </select>
            <select v-model="actionAccountId" 
                    v-if="newTransfer.transferType.id==2"
                    style="min-width:300px">
                <option v-for="account in accounts" :key="account.id"  
                    :value="account.id"
                    >{{ account.user.username }}</option>
            </select>
        </div>
        <div>
            <input class="message-input" type="text" placeholder="Message about the awesome transfer" 
            v-model.number="newTransfer.message"
            style="width:300px" />
        </div>
        <div>
            <input class="amount-input" type="text" placeholder="Amount" 
            v-model.number="newTransfer.amount"
            style="width:60px" />
        </div>
            <button type="submit" class="btn btn-submit">Save</button>
        </form>
    </div>
</template>

<script>
import accountService from '../services/AccountService';
import transferService from '../services/TransferService';

export default {
    data(){
            return {
                newTransfer:{
                    amount:0,
                    accountTo:{
                        user:{}
                    },
                    accountFrom:{
                        user:{}
                    },
                    transferType: {
                        id:0,                        
                        desc:""
                    },
                    transferStatus: {
                        id:0,                        
                        desc:""
                    }
            },
            accounts:[],
            currentAccount:{

            },
            actionAccountId:0
        }
    },
    methods:{
        saveTransfer(){
            const actionAccount = this.accounts.find((account)=>{
                return account.id===parseInt(this.actionAccountId);
            })
            if (parseInt(this.newTransfer.transferType.id)===1){
                //request
                this.newTransfer.accountTo=this.currentAccount;
                this.newTransfer.accountFrom=actionAccount;
            } else {            
                this.newTransfer.accountFrom=this.currentAccount;                
                this.newTransfer.accountTo=actionAccount;
            }
            
            transferService.saveTransfer(this.newTransfer).then((response)=>{
                console.log(response.data);
                this.$router.push('/');
            })
            return;
        }
    },
    created(){
        accountService.getAccounts().then((response)=>{
            this.accounts = response.data;
        });
        accountService.getAccountDetail().then((response)=>{
            this.currentAccount = response.data;
        });
    }
}
</script>

<style>

</style>

// sample_application_tenmo/frontend-react-tenmo-client/src/components/ui/TransferFunds.js
import { useState, useEffect } from 'react';
import {saveTransfer} from "../../api/TransferService";
import { useNavigate } from "react-router-dom";
import { getAccountDetail, getAccounts } from '../../api/AccountService';

const TransferFunds = () => {
    const navigate = useNavigate();
    const defaultTransfer = {
            amount:"0",
            accountTo:{
                user:{}
            },
            accountFrom:{
                user:{}
            },
            transferType: {
                id:0,                        
                desc:""
            },
            transferStatus: {
                id:0,                        
                desc:""
            }
    };
    const [newTransfer, setNewTransfer] = useState(defaultTransfer);
    const [actionAccountId, setActionAccountId] = useState("");
    const [accounts, setAccounts] = useState([]);
    const [currentAccount, setCurrentAccount] = useState({});
    const [transferTypeId, setTransferTypeId] = useState("");
    const [callingAccounts, setCallingAccounts] = useState(-1);
    const [amount, setAmount] = useState(0);
    const [message, setMessage] = useState("");

    const onInputchange = (event) => {
        if (event !== undefined) event.preventDefault();        
        let localTransfer = newTransfer;
        if ((event.target.name==="transferTypeId")){
            localTransfer.transferType.id = parseInt(event.target.value);
            setTransferTypeId(event.target.value);            
        } else if ((event.target.name==="amount")){
            localTransfer.amount = parseInt(event.target.value);
            setAmount(parseInt(event.target.value));
        } else if ((event.target.name==="message")){
            localTransfer.message = event.target.value;
            setMessage(event.target.value);
        }         
        console.log(localTransfer);
        setNewTransfer(localTransfer);        
    };
    
    
    const saveCurrentTransfer = (event) => {
        if (event !== undefined) event.preventDefault();
        const actionAccount = accounts.find((account)=>{
            return account.id===parseInt(actionAccountId);
        })
        if (transferTypeId==="1"){
            newTransfer.accountTo=currentAccount;
            newTransfer.accountFrom=actionAccount;
        } else {            
            newTransfer.accountFrom=currentAccount;                
            newTransfer.accountTo=actionAccount;
        }
        
        saveTransfer(newTransfer).then(updatedTransfer => {
            navigate('/');
        });       
        
    }     
    
    const onAccountChange = (event) => {
        if (event !== undefined) event.preventDefault();
        setActionAccountId(event.target.value);
    };

    
    useEffect(() => {
        const getLocalAccounts = async () => {
            const localAccountList = async () => {
              if (callingAccounts<0) {
                setCallingAccounts(0);
                const localAccounts = await getAccounts();
                const localDetail = await getAccountDetail();
                setAccounts(localAccounts);
                setCurrentAccount(localDetail);
                if (localAccounts.length>0) {
                    setActionAccountId(localAccounts[0].id);
                }
                setCallingAccounts(1);
              }
            }
            await localAccountList();
          };
          if (callingAccounts<0) {
            getLocalAccounts()
          }
     }, [callingAccounts]);


    return (
        <>
          <div>
            <form className="new-transfer-form" onSubmit={saveCurrentTransfer}>
                <div>
                    <select value={transferTypeId}  onChange={onInputchange}
                    style={{minWidth:'300px'}} name="transferTypeId">
                            <option value="0"></option>
                            <option value="1">Request</option>
                            <option value="2">Send</option>
                    </select>
                </div>
                <div>
                    {(transferTypeId==="1") && 
                        <select value={actionAccountId}  onChange={onAccountChange}
                                style={{minWidth:'300px'}}>
                            {accounts.map(account =>
                            <option key={account.id}
                                value={account.id}
                                >{ account.user.username }</option>
                            )}
                        </select>
                    }
                    {(transferTypeId==="2") && 
                        <select value={actionAccountId}  onChange={onAccountChange}
                                style={{minWidth:'300px'}}>
                            {accounts.map(account =>
                            <option key={account.id}
                                value={account.id}
                                >{ account.user.username }</option>
                            )}
                        </select>
                    }
                </div>
                <div>
                    <input className="message-input" type="text" placeholder="Message about the awesome transfer" 
                        value={message}  onChange={onInputchange}
                        style={{width:'300px'}} name="message"/>
                </div>
                <div>
                    <input className="amount-input" type="number" placeholder="Amount"
                    value={amount}  onChange={onInputchange}
                    style={{width:'100px'}} name="amount"/>
                </div>
                <button type="submit" className="btn btn-submit">Save</button>
            </form>
        </div>
        </>
    );
}
export default TransferFunds;
